<style>
    html,
    body {
        color: var(--color-site-body-text);
    }

    input,
    textarea,
    select,
    button {
        color: inherit;
    }

    h1,
    h2,
    h3,
    h4,
    h5,
    h6,
    .site-heading-text.site-heading-text,
    .site-heading-text.site-heading-text span,
    .site-heading-text.site-heading-text strong,
    .site-heading-text.site-heading-text em,
    .site-heading-text.site-heading-text small,
    h1.site-heading-text,
    h2.site-heading-text,
    h3.site-heading-text,
    h4.site-heading-text,
    h5.site-heading-text,
    h6.site-heading-text {
        color: var(--color-site-text) !important;
    }

    h1 span,
    h1 strong,
    h1 em,
    h1 small,
    h2 span,
    h2 strong,
    h2 em,
    h2 small,
    h3 span,
    h3 strong,
    h3 em,
    h3 small,
    h4 span,
    h4 strong,
    h4 em,
    h4 small,
    h5 span,
    h5 strong,
    h5 em,
    h5 small,
    h6 span,
    h6 strong,
    h6 em,
    h6 small {
        color: inherit !important;
    }

    p,
    li,
    dd,
    dt,
    td,
    figcaption,
    blockquote,
    label,
    small,
    time,
    .site-body-text.site-body-text,
    p.site-body-text,
    div.site-body-text,
    span.site-body-text,
    .site-body-text.site-body-text p,
    .site-body-text.site-body-text li,
    .site-body-text.site-body-text dd,
    .site-body-text.site-body-text dt,
    .site-body-text.site-body-text td,
    .site-body-text.site-body-text figcaption,
    .site-body-text.site-body-text blockquote,
    .site-body-text.site-body-text span,
    .site-body-text.site-body-text div,
    .site-body-text.site-body-text strong,
    .site-body-text.site-body-text em,
    .site-body-text.site-body-text small,
    .product-detail-description.product-detail-description,
    .product-detail-description p,
    .product-detail-description li,
    .product-detail-description dd,
    .product-detail-description dt,
    .product-detail-description td,
    .product-detail-description figcaption,
    .product-detail-description blockquote,
    .product-detail-description span,
    .product-detail-description div,
    .product-detail-description strong,
    .product-detail-description em,
    .product-detail-description small,
    p.text-gray-400,
    p.text-gray-500,
    p.text-gray-600,
    p.text-gray-700,
    p.text-gray-800,
    p.text-gray-900,
    p.site-body-text.text-gray-400,
    p.site-body-text.text-gray-500,
    p.site-body-text.text-gray-600,
    p.site-body-text.text-gray-700,
    p.site-body-text.text-gray-800,
    p.site-body-text.text-gray-900,
    div.site-body-text.text-gray-400,
    div.site-body-text.text-gray-500,
    div.site-body-text.text-gray-600,
    div.site-body-text.text-gray-700,
    div.site-body-text.text-gray-800,
    div.site-body-text.text-gray-900,
    span.site-body-text.text-gray-400,
    span.site-body-text.text-gray-500,
    span.site-body-text.text-gray-600,
    span.site-body-text.text-gray-700,
    span.site-body-text.text-gray-800,
    span.site-body-text.text-gray-900 {
        color: var(--color-site-body-text) !important;
    }
</style>
